### ISSUE TITLE
Clarification on documentation for chartist plugins

### ISSUE THREAD

**Issue by caseylargent** [jherdman/ember-cli-chartist#78] opened 2018-09-20 04:59 UTC
Can you update the documentation to include instructions on how to include chartist plugins? I currently am not able to get it to work in my ember application.

**Comment by jherdman** [comment] 2018-09-20 12:38
Hi @caseylargent ! This is a long sought after request (see also #31). I'm a bit short on bandwidth to do this right now. If you have any breakthroughs a pull request would be greatly appreciated by all ❤️ .

In the mean time I'm going to close this as it's a duplicate of #31.

**Closed by jherdman** 2018-09-20 12:38 UTC
